/**
 * 应用程序样式定义
 * 使用 Fluent UI 的 makeStyles 创建样式对象
 */

import { makeStyles, shorthands } from "@fluentui/react-components";
import { MergeClasses } from "@fluentui/react-components";

type ClassDictionary = MergeClasses<never>;

export const useStyles = makeStyles({
    root: {
        display: 'flex',
        flexDirection: 'row',
        height: '100vh',
        backgroundColor: 'var(--colorNeutralBackground1)',
        fontFamily: '"Segoe UI Variable Display", "Segoe UI", "Microsoft YaHei", sans-serif',
    },
    sidebar: {
        width: 'auto',
        minWidth: 'fit-content',
        ...shorthands.padding('8px', '0', '12px', '0'),
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'var(--colorNeutralBackground2)',
        boxShadow: 'inset -1px 0 0 0 var(--colorNeutralStroke2)',
    },
    header: {
        display: 'flex',
        alignItems: 'center',
        paddingLeft: '16px',
        paddingTop: '12px',
        paddingBottom: '12px',
        gap: '12px',
    },
    appIcon: {
        fontSize: '20px',
        color: 'var(--colorCompoundBrandStroke)',
    },
    headerTitle: {
        fontSize: '14px',
        fontWeight: '400',
    },
    menuButton: {
        ...shorthands.margin('4px', '4px', '12px', '4px'),
        minWidth: '40px',
        height: '36px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'default',
        ...shorthands.borderRadius('4px'),
        fontSize: '18px',
        ':hover': {
            backgroundColor: 'var(--colorNeutralBackground1Hover)',
        }
    },
    tabList: {
        rowGap: '2px',
        position: 'relative',
        cursor: 'default',
        '& .fui-TabList__indicator': {
            display: 'none !important',
        },
        '& .fui-Tab__indicator': {
            display: 'none !important',
        },
        '& .fui-TabList__indicatorSelected': {
            display: 'none !important',
        },
    },
    activeIndicator: {
        position: 'absolute',
        left: '8px',
        width: '3px',
        height: '20px',
        backgroundColor: 'var(--colorBrandStroke1)',
        ...shorthands.borderRadius('2px'),
        zIndex: 10,
        transitionProperty: 'transform, opacity',
        transitionDuration: '300ms',
        transitionTimingFunction: 'cubic-bezier(0.33, 0, 0.67, 1)',
        pointerEvents: 'none',
        top: '12px',
    },
    tab: {
        height: '40px',
        minHeight: '40px',
        ...shorthands.borderRadius('4px'),
        ...shorthands.margin('2px', '8px'),
        ...shorthands.padding('0px', '12px', '0px', '12px'),
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'flex-start',
        position: 'relative',
        cursor: 'default',
        backgroundColor: 'transparent',
        transitionProperty: 'background-color, color, transform',
        transitionDuration: '150ms',
        boxSizing: 'border-box',
        ':hover': {
            backgroundColor: 'var(--colorNeutralBackground1Hover)',
        },
        ':active': {
            backgroundColor: 'var(--colorNeutralBackground1Selected)',
            transform: 'scale(0.98)',
        },
        '&::after': {
            display: 'none !important',
        },
        '&::before': {
            display: 'none !important',
        },
        '& .fui-Tab__indicator': {
            display: 'none !important',
        },
    },
    tabSelected: {
        backgroundColor: 'var(--colorNeutralBackground1Selected) !important',
        color: 'var(--colorNeutralForeground1Selected) !important',
        fontWeight: '600',
        '&:hover': {
            backgroundColor: 'var(--colorNeutralBackground1Hover) !important',
        },
        '&:active': {
            backgroundColor: 'var(--colorNeutralBackground1Selected) !important',
            opacity: 0.8,
        }
    },
    tabIcon: {
        fontSize: '20px',
        width: '20px',
        height: '20px',
        marginRight: '12px',
        marginLeft: '12px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    divider: {
        height: '1px',
        backgroundColor: 'var(--colorNeutralStroke2)',
        ...shorthands.margin('12px', '16px'),
    },
    main: {
        flexGrow: 1,
        ...shorthands.padding('32px', '24px'),
        overflowY: 'auto',
        overflowX: 'hidden',
        minWidth: 0,
    },
    section: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        maxWidth: '1000px',
    },
    card: {
        width: '100%',
        boxSizing: 'border-box',
        ...shorthands.padding('16px', '24px'),
        backgroundColor: 'var(--colorNeutralBackground1)',
        ...shorthands.border('1px', 'solid', 'var(--colorNeutralStroke2)'),
        ...shorthands.borderRadius('4px'),
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        gap: '20px',
        ':hover': {
            backgroundColor: 'var(--colorNeutralBackground1Hover)',
        }
    },
    groupTitle: {
        fontSize: '14px',
        fontWeight: '600',
        marginTop: '24px',
        marginBottom: '8px',
        color: 'var(--colorNeutralForeground1)',
    },
    sectionHeader: {
        marginBottom: '20px',
    },
    title: {
        fontSize: '28px',
        fontWeight: '600',
        marginBottom: '8px',
        lineHeight: '1.2',
    },
    description: {
        color: 'var(--colorNeutralForeground2)',
        fontSize: '14px',
        lineHeight: '1.5',
    },
    formGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
        minWidth: 0,
        width: '100%',
        boxSizing: 'border-box',
    },
    switchRow: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    label: {
        fontSize: '14px',
        fontWeight: '500',
    },
    footer: {
        marginTop: '40px',
        display: 'flex',
        justifyContent: 'flex-end',
        ...shorthands.padding('0', '0', '40px', '0'),
    },
    rangeContainer: {
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
        marginTop: '4px',
    },
    rangeValue: {
        minWidth: '48px',
        fontSize: '14px',
        fontWeight: '600',
        color: 'var(--colorBrandForeground1)',
        textAlign: 'right',
    },
    helpText: {
        color: 'var(--colorNeutralForeground3)',
        fontSize: '12px',
        marginTop: '4px',
    },
    componentSettingsSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        maxWidth: 'none',
        height: '100%',
        overflow: 'hidden',
        width: '100%',
        minWidth: 0,
        boxSizing: 'border-box',
    },
    componentLayout: {
        display: 'flex',
        flexDirection: 'row',
        gap: '0',
        flexGrow: 1,
        minHeight: '0',
        position: 'relative',
        overflow: 'hidden',
        width: '100%',
        minWidth: 0,
    },
    leftPanel: {
        display: 'flex',
        flexDirection: 'column',
        minHeight: 0,
        overflow: 'hidden',
        ...shorthands.margin('0', '12px', '0', '0'),
        boxSizing: 'border-box',
        height: '100%',
        flexShrink: 0,
        minWidth: 0,
    },
    rightPanel: {
        display: 'flex',
        flexDirection: 'column',
        minHeight: 0,
        overflow: 'hidden',
        ...shorthands.margin('0', '0', '0', '12px'),
        boxSizing: 'border-box',
        height: '100%',
        flexShrink: 0,
        minWidth: 0,
    },
    resizer: {
        width: '4px',
        backgroundColor: 'var(--colorNeutralStroke1)',
        cursor: 'col-resize',
        position: 'relative',
        transitionProperty: 'background-color, transform',
        transitionDuration: '150ms',
        transitionTimingFunction: 'ease',
        flexShrink: 0,
        flexGrow: 0,
        zIndex: 10,
        ':hover': {
            backgroundColor: 'var(--colorBrandStroke1)',
            transform: 'scaleX(1.5)',
        },
        ':active': {
            backgroundColor: 'var(--colorBrandBackground2Pressed)',
            transform: 'scaleX(1.5)',
        },
        '&::after': {
            content: '""',
            position: 'absolute',
            top: '50%',
            left: '50%',
            transform: 'translate(-50%, -50%)',
            width: '2px',
            height: '24px',
            backgroundColor: 'var(--colorNeutralForeground3)',
            borderRadius: '1px',
            opacity: 0.5,
            transitionProperty: 'opacity, background-color',
            transitionDuration: '150ms',
        },
        ':hover::after': {
            backgroundColor: 'var(--colorNeutralForeground1)',
            opacity: 1,
        },
        ':active::after': {
            backgroundColor: 'var(--colorBrandForeground1)',
            opacity: 1,
        },
    },
    previewPanel: {
        flex: 1,
        backgroundColor: 'var(--colorNeutralBackground2)',
        ...shorthands.borderRadius('8px'),
        ...shorthands.border('1px', 'solid', 'var(--colorNeutralStroke1)'),
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
        ...shorthands.overflow('hidden'),
        height: '100%',
        width: '100%',
    },
    propertiesPanel: {
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'var(--colorNeutralBackground2)',
        ...shorthands.borderRadius('8px'),
        ...shorthands.border('1px', 'solid', 'var(--colorNeutralStroke1)'),
        ...shorthands.overflow('hidden'),
        height: '100%',
        width: '100%',
        minWidth: 0,
    },
    propertiesContent: {
        ...shorthands.padding('16px'),
        flexGrow: 1,
        ...shorthands.overflow('auto'),
        minWidth: 0,
        width: '100%',
        boxSizing: 'border-box',
    },
    propertySection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        marginTop: '16px',
        minWidth: 0,
        width: '100%',
        boxSizing: 'border-box',
    },
    previewPlaceholder: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '12px',
        color: 'var(--colorNeutralForeground4)',
    },
    editorPanel: {
        width: '460px',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'var(--colorNeutralBackground1)',
        ...shorthands.borderRadius('8px'),
        ...shorthands.border('1px', 'solid', 'var(--colorNeutralStroke1)'),
        ...shorthands.overflow('hidden'),
    },
    tabContent: {
        ...shorthands.padding('16px'),
        flexGrow: 1,
        ...shorthands.overflow('auto'),
    },
    widgetList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        width: '100%',
        ...shorthands.padding('24px'),
        boxSizing: 'border-box',
    },
    widgetItem: {
        backgroundColor: 'var(--colorNeutralBackground1)',
        ...shorthands.border('1px', 'solid', 'var(--colorNeutralStroke1)'),
        ...shorthands.borderRadius('6px'),
        ...shorthands.padding('12px', '16px'),
        boxShadow: 'var(--shadow2)',
        cursor: 'default',
        transitionProperty: 'background-color, border-color, box-shadow, transform',
        transitionDuration: '150ms',
        position: 'relative',
        ':hover': {
            backgroundColor: 'var(--colorNeutralBackground1Hover)',
            ...shorthands.borderColor('var(--colorBrandStroke1)'),
            boxShadow: 'var(--shadow4)',
        },
        ':active': {
            transform: 'scale(0.995)',
        }
    },
    widgetItemSelected: {
        backgroundColor: 'var(--colorNeutralBackground1Hover)',
        ...shorthands.borderColor('var(--colorBrandStroke1)'),
        ...shorthands.borderWidth('2px'),
        boxShadow: 'var(--shadow8)',
    },
    widgetDragging: {
        opacity: 0.4,
        ...shorthands.border('1px', 'dashed', 'var(--colorBrandStroke1)'),
        boxShadow: 'none',
    },
    widgetDragOver: {
        position: 'relative',
        '&::before': {
            content: '""',
            position: 'absolute',
            top: '-8px',
            left: '0',
            right: '0',
            height: '3px',
            backgroundColor: 'var(--colorBrandStroke1)',
            borderRadius: '2px',
            boxShadow: '0 0 4px var(--colorBrandStroke1)',
            zIndex: 10,
        }
    },
    widgetDropZone: {
        height: '24px',
        marginTop: '-12px',
        width: '100%',
        position: 'relative',
        cursor: 'default',
    },
    widgetDropZoneDragOver: {
        '&::before': {
            content: '""',
            position: 'absolute',
            bottom: '0',
            left: '0',
            right: '0',
            height: '3px',
            backgroundColor: 'var(--colorBrandStroke1)',
            borderRadius: '2px',
            boxShadow: '0 0 4px var(--colorBrandStroke1)',
            zIndex: 10,
        }
    },
    widgetType: {
        fontWeight: '600',
        fontSize: '14px',
        color: 'var(--colorNeutralForeground1)',
        display: 'block',
        marginBottom: '2px',
    },
    widgetInfo: {
        fontSize: '12px',
        color: 'var(--colorNeutralForeground3)',
    },
    propertyGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0px',
        marginTop: '0px',
        minWidth: 0,
        width: '100%',
        boxSizing: 'border-box',
    },
    propertyRow: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    propertyLabel: {
        fontSize: '14px',
        fontWeight: '600',
    },
    panelTitle: {
        marginTop: '0px',
        marginBottom: '10px',
    },
    sectionTitle: {
        fontSize: '16px',
        fontWeight: '600',
        marginTop: '10px',
    },
    libraryGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
        gap: '16px',
        marginTop: '16px',
    },
    libraryItem: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        padding: '16px',
        gap: '16px',
        backgroundColor: 'var(--colorNeutralBackground1)',
        border: '1px solid var(--colorNeutralStroke1)',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'all 0.2s cubic-bezier(0.33, 0, 0.67, 1)',
        ':hover': {
            backgroundColor: 'var(--colorNeutralBackground1Hover)',
            borderColor: 'var(--colorBrandStroke1)',
            transform: 'translateY(-2px)',
            boxShadow: 'var(--shadow4)',
        }
    },
    libraryItemIcon: {
        fontSize: '32px',
        color: 'var(--colorBrandForeground1)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    libraryItemContent: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    libraryItemTitle: {
        fontSize: '14px',
        fontWeight: '600',
        color: 'var(--colorNeutralForeground1)',
    },
    libraryItemDesc: {
        fontSize: '12px',
        color: 'var(--colorNeutralForeground3)',
        lineHeight: '1.4',
    },
    colorPickerContainer: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        marginTop: '4px',
    },
    colorInput: {
        width: '48px',
        height: '32px',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
        padding: '0',
        backgroundColor: 'transparent',
    },
    colorValue: {
        fontSize: '14px',
        fontWeight: '600',
        color: 'var(--colorBrandForeground1)',
        fontFamily: 'monospace',
    }
});
